import { Product } from "@/types/products";

export const products: Product[] = [
  {
    id: 1,
    category: "Processors",
    name: "AMD Ryzen 5 7600",
    specs: ["6 Cores", "12 Threads", "AM5"],
    price: 58999,
    compareAtPrice: 62999,
    badge: "Popular",
    available: true,
  },
  {
    id: 2,
    category: "Graphics Cards",
    name: "RTX 4060 8GB",
    specs: ["8GB GDDR6", "DLSS 3", "PCIe 4.0"],
    price: 104999,
    badge: "In stock",
    available: true,
  },
  {
    id: 3,
    category: "Memory",
    name: "Corsair Vengeance 16GB",
    specs: ["DDR5", "5600MHz", "CL36"],
    price: 13999,
    compareAtPrice: 15999,
    available: true,
  },
  {
    id: 4,
    category: "Storage",
    name: "Samsung 990 EVO 1TB",
    specs: ["1TB", "NVMe", "PCIe 4.0"],
    price: 21999,
    badge: "Staff pick",
    available: true,
  },
  {
    id: 5,
    category: "Power Supply",
    name: "Corsair RM750e",
    specs: ["750W", "80+ Gold", "Fully Modular"],
    price: 32999,
    available: true,
  },
  {
    id: 6,
    category: "Cooling",
    name: "DeepCool AK400",
    specs: ["120mm", "180W TDP", "4 Heatpipes"],
    price: 9499,
    available: true,
  },
  {
    id: 7,
    category: "Peripherals",
    name: "Logitech G502 Hero",
    specs: ["25K DPI", "11 Buttons", "RGB"],
    price: 16999,
    available: true,
  },
  {
    id: 8,
    category: "Graphics Cards",
    name: "RX 7600 XT 16GB",
    specs: ["16GB GDDR6", "RDNA 3", "PCIe 4.0"],
    price: 119999,
    badge: "New",
    available: false,
  },
];